# Automatically generated by create_hash_dict "--output" "tools/bazel_hash_dict.bzl"

BAZEL_HASH_DICT = {
    "0.11.0": {
        "darwin-x86_64": "8d60c3944ccd220f71bcbf034e416f0000f196cecae2dfd3661a181e22565b65",
        "linux-x86_64": "687305c38a7786f3f4d74e13f31a05ae2a5ef50ef1736f85b749ec047a97e73b",
    },
    "0.12.0": {
        "darwin-x86_64": "a1e0e08959880de3c360006718332b6426afa40a09b4353aae552e40f411d0ee",
        "linux-x86_64": "1af7a70cc2c5180765ed2f0da366c625fac89e6656dedc008320d46eb1f75e20",
    },
    "0.13.1": {
        "darwin-x86_64": "7eca890f253d64a334108db7017214693a87d4af1cd7c6239b1b89fa4a9dd802",
        "linux-x86_64": "a2f2ef984193119663afeb4b8cecf2847bfec578d2f1f9256c403589cc52465d",
    },
    "0.14.1": {
        "darwin-x86_64": "0bdf63909ef9ba446a2d7cd077edb3aaf4d63b725e82e7cdcb69df482df61a3c",
        "linux-x86_64": "7b14e4fc76bf85c4abf805833e99f560f124a3b96d56e0712c693e94e19d1376",
    },
    "0.15.2": {
        "darwin-x86_64": "84ee271274e7c8904a48f7894fe0569174d162c7428a19dda57fc6a6c95c628b",
        "linux-x86_64": "13eae0f09565cf17fc1c9ce1053b9eac14c11e726a2215a79ebaf5bdbf435241",
    },
    "0.16.1": {
        "darwin-x86_64": "07d5c753738c7186117168770f525b59c39b24103f714be2ffcaadd8e2c53a78",
        "linux-x86_64": "17ab70344645359fd4178002f367885e9019ae7507c9c1ade8220f3628383444",
    },
}
