# Automatically generated by create_hash_dict

BAZEL_HASH_DICT = {
    "0.15.2": {
        "darwin-x86_64": "84ee271274e7c8904a48f7894fe0569174d162c7428a19dda57fc6a6c95c628b",
        "linux-x86_64": "13eae0f09565cf17fc1c9ce1053b9eac14c11e726a2215a79ebaf5bdbf435241",
    },
    "0.16.0": {
        "darwin-x86_64": "bb4720c027a991643be7dabee5c96a84c3776d6e2da92bf65df012a7cec15569",
        "linux-x86_64": "bdef5499ea21baa69e707391b463105b32c4a2fbf1ab045da53f4023c1a033be",
    },
    "0.16.1": {
        "darwin-x86_64": "07d5c753738c7186117168770f525b59c39b24103f714be2ffcaadd8e2c53a78",
        "linux-x86_64": "17ab70344645359fd4178002f367885e9019ae7507c9c1ade8220f3628383444",
    },
    "0.17.1": {
        "darwin-x86_64": "6a75339b042ed0bc8ad67f017395e9032f253b241190e3050ba55e4255fde2d8",
        "linux-x86_64": "feedbe02c81142ed95ef8d380472f0a0d88e1b9a4b1fb6e21728701032b68e02",
    },
    "0.17.2": {
        "darwin-x86_64": "f5276007719eee0f29904a3a640383cdba99db9fba40b6a3684ca3098ddeb3c7",
        "linux-x86_64": "31fac8b2edcc6d95f1afb21725f604479eb440596e7fc7554fd47e293020ced9",
    },
    "0.18.0": {
        "darwin-x86_64": "6f07346c72d9eaea0561386a1dc49ae0b8a60f39b180cbbab930e705f3d7a3c4",
        "linux-x86_64": "48ddaa9c9fef73dbe68517f274f09b33c3c8fdf3410638808b609f82b177d397",
    },
    "0.18.1": {
        "darwin-x86_64": "ed9671b5a78c1f7cbaa3b36abcb9329dbfa869fae4593adec4acc3d07315b7cc",
        "linux-x86_64": "8073657ced2bb323dd2e7ba6e39011ca56b856cae475b476e9b77d30123582e5",
    },
    "0.19.0": {
        "darwin-x86_64": "2a3e309fe359bd8beca18b2ab095969208df1c73bc4002d92341d0fff83b4a01",
        "linux-x86_64": "b9e988643b10444d6d8eb04461418b7b80e3d171e12d1c8b6e2a50f541e739e7",
    },
    "0.19.1": {
        "darwin-x86_64": "e2812cd69483b993a0ca1ab13771f7667645b99e41ee007265cf65c681b568da",
        "linux-x86_64": "f2fdd4b0c0ef7cabee2955f77caae51d3c3f6d1569e8257a349a1236f0905ce6",
    },
    "0.19.2": {
        "darwin-x86_64": "25ea85d4974ead87a7600e17b733bf8035a075fc8671c97e1c1f7dc8ff304231",
        "linux-x86_64": "42ba631103011594cdf5591ef07658a9e9a5d73c5ee98a9f09651ac4ac535d8c",
    },
    "0.20.0": {
        "darwin-x86_64": "45089aa2417d5dd82578cb851220e55f897ad42988bbf71cfa4e1f2126c11854",
        "linux-x86_64": "44aed3bd8e58a889ee36f187a4b1cb573a2b4cc7a3d7c0cf0696205764e45dec",
    },
    "0.21.0": {
        "darwin-x86_64": "5e40dcf12a18990ffe5830fb5c83297aed090fd6e6c7c5b2eb720c19a33044fc",
        "linux-x86_64": "328d5fa87a61e1f6e674a8f88c5ae54b8987eaf5a6c944257600c5029c8feef8",
    },
    "0.22.0": {
        "darwin-x86_64": "adae5bbc3bf2b9b60d460d8ea2c65da1a6edd75b242439dfc49d001272548d13",
        "linux-x86_64": "6d85f9fd6671ec5ffa8c78d150fe6c8da50874cfa8aa1900672dfd93e9989cb0",
    },
}
