# Automatically generated by create_bazel_version_dict '--output' './tools/bazel_version_dict.bzl'

BAZEL_VERSION_DICT = {
    "0.15.2": {
        "darwin-x86_64": {
            "url": "http://releases.bazel.build/0.15.2/release/bazel-0.15.2-installer-darwin-x86_64.sh",
            "sha256": "84ee271274e7c8904a48f7894fe0569174d162c7428a19dda57fc6a6c95c628b",
        },
        "linux-x86_64": {
            "url": "http://releases.bazel.build/0.15.2/release/bazel-0.15.2-installer-linux-x86_64.sh",
            "sha256": "13eae0f09565cf17fc1c9ce1053b9eac14c11e726a2215a79ebaf5bdbf435241",
        },
        "windows-x86_64": {
            "url": "http://releases.bazel.build/0.15.2/release/bazel-0.15.2-windows-x86_64.zip",
            "sha256": "37b1eb9b782c4ca89f5c5951144f7b953341bdb7e3d2c10f60e36f82a872559d",
        },
    },
    "0.16.0": {
        "darwin-x86_64": {
            "url": "http://releases.bazel.build/0.16.0/release/bazel-0.16.0-installer-darwin-x86_64.sh",
            "sha256": "bb4720c027a991643be7dabee5c96a84c3776d6e2da92bf65df012a7cec15569",
        },
        "linux-x86_64": {
            "url": "http://releases.bazel.build/0.16.0/release/bazel-0.16.0-installer-linux-x86_64.sh",
            "sha256": "bdef5499ea21baa69e707391b463105b32c4a2fbf1ab045da53f4023c1a033be",
        },
        "windows-x86_64": {
            "url": "http://releases.bazel.build/0.16.0/release/bazel-0.16.0-windows-x86_64.zip",
            "sha256": "01787fc5a71a1315a1369bf81db79f8787ecaf542ed6958791f584143cd91129",
        },
    },
    "0.16.1": {
        "darwin-x86_64": {
            "url": "http://releases.bazel.build/0.16.1/release/bazel-0.16.1-installer-darwin-x86_64.sh",
            "sha256": "07d5c753738c7186117168770f525b59c39b24103f714be2ffcaadd8e2c53a78",
        },
        "linux-x86_64": {
            "url": "http://releases.bazel.build/0.16.1/release/bazel-0.16.1-installer-linux-x86_64.sh",
            "sha256": "17ab70344645359fd4178002f367885e9019ae7507c9c1ade8220f3628383444",
        },
        "windows-x86_64": {
            "url": "http://releases.bazel.build/0.16.1/release/bazel-0.16.1-windows-x86_64.zip",
            "sha256": "47f9a7f70801f731727412a8b80ab6b350e9302f61b4d70dee8d9479647d7917",
        },
    },
    "0.17.1": {
        "darwin-x86_64": {
            "url": "http://releases.bazel.build/0.17.1/release/bazel-0.17.1-installer-darwin-x86_64.sh",
            "sha256": "6a75339b042ed0bc8ad67f017395e9032f253b241190e3050ba55e4255fde2d8",
        },
        "linux-x86_64": {
            "url": "http://releases.bazel.build/0.17.1/release/bazel-0.17.1-installer-linux-x86_64.sh",
            "sha256": "feedbe02c81142ed95ef8d380472f0a0d88e1b9a4b1fb6e21728701032b68e02",
        },
        "windows-x86_64": {
            "url": "http://releases.bazel.build/0.17.1/release/bazel-0.17.1-windows-x86_64.zip",
            "sha256": "ba6ad8931f1c82095a1194976f01adfafd881ee69fc69665334104c661800b4b",
        },
    },
    "0.17.2": {
        "darwin-x86_64": {
            "url": "http://releases.bazel.build/0.17.2/release/bazel-0.17.2-installer-darwin-x86_64.sh",
            "sha256": "f5276007719eee0f29904a3a640383cdba99db9fba40b6a3684ca3098ddeb3c7",
        },
        "linux-x86_64": {
            "url": "http://releases.bazel.build/0.17.2/release/bazel-0.17.2-installer-linux-x86_64.sh",
            "sha256": "31fac8b2edcc6d95f1afb21725f604479eb440596e7fc7554fd47e293020ced9",
        },
        "windows-x86_64": {
            "url": "http://releases.bazel.build/0.17.2/release/bazel-0.17.2-windows-x86_64.zip",
            "sha256": "acb2ccec892e6eab8e07ea242fa89b73ea14dc22d17a0c8df152b27637abd166",
        },
    },
    "0.18.0": {
        "darwin-x86_64": {
            "url": "http://releases.bazel.build/0.18.0/release/bazel-0.18.0-installer-darwin-x86_64.sh",
            "sha256": "6f07346c72d9eaea0561386a1dc49ae0b8a60f39b180cbbab930e705f3d7a3c4",
        },
        "linux-x86_64": {
            "url": "http://releases.bazel.build/0.18.0/release/bazel-0.18.0-installer-linux-x86_64.sh",
            "sha256": "48ddaa9c9fef73dbe68517f274f09b33c3c8fdf3410638808b609f82b177d397",
        },
        "windows-x86_64": {
            "url": "http://releases.bazel.build/0.18.0/release/bazel-0.18.0-windows-x86_64.zip",
            "sha256": "51642560e4e8417efec6490104068215711ce05e21a8c4c4b584e8b31041dbf9",
        },
    },
    "0.18.1": {
        "darwin-x86_64": {
            "url": "http://releases.bazel.build/0.18.1/release/bazel-0.18.1-installer-darwin-x86_64.sh",
            "sha256": "ed9671b5a78c1f7cbaa3b36abcb9329dbfa869fae4593adec4acc3d07315b7cc",
        },
        "linux-x86_64": {
            "url": "http://releases.bazel.build/0.18.1/release/bazel-0.18.1-installer-linux-x86_64.sh",
            "sha256": "8073657ced2bb323dd2e7ba6e39011ca56b856cae475b476e9b77d30123582e5",
        },
        "windows-x86_64": {
            "url": "http://releases.bazel.build/0.18.1/release/bazel-0.18.1-windows-x86_64.zip",
            "sha256": "40dd3a5487d826a2c1aea936b5b07330cfe0f7ab1710fd8ef7091bf9530ec736",
        },
    },
    "0.19.0": {
        "darwin-x86_64": {
            "url": "http://releases.bazel.build/0.19.0/release/bazel-0.19.0-installer-darwin-x86_64.sh",
            "sha256": "2a3e309fe359bd8beca18b2ab095969208df1c73bc4002d92341d0fff83b4a01",
        },
        "linux-x86_64": {
            "url": "http://releases.bazel.build/0.19.0/release/bazel-0.19.0-installer-linux-x86_64.sh",
            "sha256": "b9e988643b10444d6d8eb04461418b7b80e3d171e12d1c8b6e2a50f541e739e7",
        },
        "windows-x86_64": {
            "url": "http://releases.bazel.build/0.19.0/release/bazel-0.19.0-windows-x86_64.zip",
            "sha256": "9ee25f3f0f23daf5339b357b3f2b258e42435d4912378f993222f686c66c692c",
        },
    },
}
