# Automatically generated by create_hash_dict '--output' 'tools/bazel_hash_dict.bzl'

BAZEL_HASH_DICT = {
    "0.15.2": {
        "darwin-x86_64": "84ee271274e7c8904a48f7894fe0569174d162c7428a19dda57fc6a6c95c628b",
        "linux-x86_64": "13eae0f09565cf17fc1c9ce1053b9eac14c11e726a2215a79ebaf5bdbf435241",
    },
    "0.16.0": {
        "darwin-x86_64": "bb4720c027a991643be7dabee5c96a84c3776d6e2da92bf65df012a7cec15569",
        "linux-x86_64": "bdef5499ea21baa69e707391b463105b32c4a2fbf1ab045da53f4023c1a033be",
    },
    "0.16.1": {
        "darwin-x86_64": "07d5c753738c7186117168770f525b59c39b24103f714be2ffcaadd8e2c53a78",
        "linux-x86_64": "17ab70344645359fd4178002f367885e9019ae7507c9c1ade8220f3628383444",
    },
    "0.17.1": {
        "darwin-x86_64": "6a75339b042ed0bc8ad67f017395e9032f253b241190e3050ba55e4255fde2d8",
        "linux-x86_64": "feedbe02c81142ed95ef8d380472f0a0d88e1b9a4b1fb6e21728701032b68e02",
    },
}
